## **Redes Neurais**

Dataset:
https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength

Modelagem da resistência do concreto.

In [29]:
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import MinMaxScaler

from sklearn.neural_network import MLPRegressor

from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [11]:
dados = pd.read_csv('Concrete_Data.csv', sep=';')
dados.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age Day,Concrete Strength
0,"540,0","0,0","0,0","162,0","2,5","1040,0","676,0",28,"79,99"
1,"540,0","0,0","0,0","162,0","2,5","1055,0","676,0",28,"61,89"
2,"332,5","142,5","0,0","228,0","0,0","932,0","594,0",270,"40,27"
3,"332,5","142,5","0,0","228,0","0,0","932,0","594,0",365,"41,05"
4,"198,6","132,4","0,0","192,0","0,0","978,4","825,5",360,"44,30"

In [12]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cement              1030 non-null   object
 1   Blast Furnace Slag  1030 non-null   object
 2   Fly Ash             1030 non-null   object
 3   Water               1030 non-null   object
 4   Superplasticizer    1030 non-null   object
 5   Coarse Aggregate    1030 non-null   object
 6   Fine Aggregate      1030 non-null   object
 7   Age Day             1030 non-null   int64
 8   Concrete Strength   1030 non-null   object
dtypes: int64(1), object(8)
memory usage: 72.6+ KB

In [13]:
for col in dados.columns:
    if dados[col].dtypes == 'object':
        dados[col] = dados[col].str.replace(',', '.').astype(float)
    
dados.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age Day,Concrete Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [14]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cement              1030 non-null   float64
 1   Blast Furnace Slag  1030 non-null   float64
 2   Fly Ash             1030 non-null   float64
 3   Water               1030 non-null   float64
 4   Superplasticizer    1030 non-null   float64
 5   Coarse Aggregate    1030 non-null   float64
 6   Fine Aggregate      1030 non-null   float64
 7   Age Day             1030 non-null   int64
 8   Concrete Strength   1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB

In [21]:
normalizer = MinMaxScaler(feature_range=(0, 1))

dados = pd.DataFrame({col: normalizer.fit_transform(dados[[col]])[:, 0] for col in dados.columns})
dados.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age Day,Concrete Strength
0,1.000000,0.000000,0.0,0.321086,0.07764,0.694767,0.205720,0.074176,0.967485
1,1.000000,0.000000,0.0,0.321086,0.07764,0.738372,0.205720,0.074176,0.741996
2,0.526256,0.396494,0.0,0.848243,0.00000,0.380814,0.000000,0.739011,0.472655
3,0.526256,0.396494,0.0,0.848243,0.00000,0.380814,0.000000,1.000000,0.482372
4,0.220548,0.368392,0.0,0.560703,0.00000,0.515698,0.580783,0.986264,0.522860

In [23]:
X = dados.drop(columns=['Concrete Strength'])
y = dados['Concrete Strength']

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30)

In [24]:
neural = MLPRegressor(hidden_layer_sizes=(5))

neural.fit(Xtrain, ytrain)

ypred = neural.predict(Xtest)

In [32]:
print(mean_squared_error(ytest, ypred))
print(mean_absolute_error(ytest, ypred))

0.021656778521141066
0.11934694851932676