# **RobustScaler**

### **Útil quando as variáveis possuem Outliers marginais**
* Ao contrário de **StandarScaler** que utiliza a **MÉDIA** em sua fórmula:

    **X'** *= ( X - Xmédia ) / Desvio Padrão* 

* O **RobustScaler** utiliza a **MEDIANA** em sua fórmula:

    **X'** *= ( X - Xmediana ) / IQR*

    **IQR** = Diferença Interquartílica (3º Quartil - 1º Quartil)

https://www.youtube.com/watch?v=1lCWNcR4iW0

https://www.youtube.com/watch?v=dpDq7JF7etY

In [33]:
import pandas as pd
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [41]:
# Carga dos Dados
dados = pd.read_csv( 'pima-data.csv')
dados.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,6,148,72,35,0,33.6,0.627,50,1.3790,True
1,1,85,66,29,0,26.6,0.351,31,1.1426,False
2,8,183,64,0,0,23.3,0.672,32,0.0000,True
3,1,89,66,23,94,28.1,0.167,21,0.9062,False
4,0,137,40,35,168,43.1,2.288,33,1.3790,True

In [42]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
dados['diabetes'] = encoder.fit_transform(dados['diabetes'])
dados.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,6,148,72,35,0,33.6,0.627,50,1.3790,1
1,1,85,66,29,0,26.6,0.351,31,1.1426,0
2,8,183,64,0,0,23.3,0.672,32,0.0000,1
3,1,89,66,23,94,28.1,0.167,21,0.9062,0
4,0,137,40,35,168,43.1,2.288,33,1.3790,1

In [18]:
dados.dtypes

num_preg          int64
glucose_conc      int64
diastolic_bp      int64
thickness         int64
insulin           int64
bmi             float64
diab_pred       float64
age               int64
skin            float64
diabetes          int64
dtype: object

In [51]:
dados.corr()['diabetes'].sort_values(ascending=False)

diabetes        1.000000
glucose_conc    0.466581
bmi             0.292695
age             0.238356
num_preg        0.221898
diab_pred       0.173844
insulin         0.130548
thickness       0.074752
skin            0.074752
diastolic_bp    0.065068
Name: diabetes, dtype: float64

In [57]:
X = dados.iloc[:, 0:9].drop(columns=['diab_pred', 'insulin', 'thickness', 'skin', 'diastolic_bp'], axis=1)
y = dados.iloc[:, 9]

In [58]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.30, random_state=50)

In [59]:
escaler = RobustScaler()
X_train_scaler = escaler.fit_transform(Xtrain)
X_test_scaler  = escaler.fit_transform(Xtest)

In [60]:
from sklearn.neighbors import KNeighborsClassifier

modelo = KNeighborsClassifier()
modelo.fit(X_train_scaler, ytrain)

ypred = modelo.predict(X_test_scaler)

In [61]:
print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           0       0.76      0.82      0.79       148
           1       0.62      0.54      0.58        83

    accuracy                           0.72       231
   macro avg       0.69      0.68      0.68       231
weighted avg       0.71      0.72      0.71       231