In [13]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
from sklearn.preprocessing import MinMaxScaler

In [2]:
dados = pd.read_csv('parkinsons.data')
dados.head()

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,...,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,...,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [3]:
dados.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [4]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    object
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.7+ KB

In [25]:
X = dados.drop(columns=['name', 'status'], axis=1)
y = dados['status']

scaler = MinMaxScaler((-1,1))
X_scaler = scaler.fit_transform(X)

Xtrain, Xtest, ytrain, ytest = train_test_split(X_scaler, y, test_size=0.2, random_state=7)

In [30]:
labels = y
print(labels[labels == 1].shape[0], labels[labels == 0].shape[0])

147 48

In [26]:
pd.DataFrame(X_scaler, columns=X.columns).head()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
0,-0.631383,-0.774817,-0.890370,-0.608640,-0.501976,-0.709056,-0.504823,-0.709424,-0.375571,-0.439606,...,-0.655104,-0.334831,-0.863386,0.023490,-0.261689,0.920297,0.139750,0.171530,-0.218677,-0.005381
1,-0.603346,-0.810139,-0.443354,-0.491741,-0.422925,-0.617534,-0.352626,-0.617916,-0.054227,-0.110929,...,-0.441152,0.032097,-0.881338,-0.134845,-0.058339,0.954049,0.406554,0.482674,-0.053710,0.342652
2,-0.669923,-0.881744,-0.469423,-0.439644,-0.343874,-0.541426,-0.261522,-0.541178,-0.218733,-0.347576,...,-0.560303,-0.113365,-0.920807,-0.007559,-0.191168,1.000000,0.273489,0.372742,-0.182361,0.193365
3,-0.669993,-0.854145,-0.471599,-0.473316,-0.343874,-0.581888,-0.350482,-0.582276,-0.171444,-0.290058,...,-0.532430,-0.049044,-0.918006,-0.008128,-0.167490,0.951770,0.391255,0.476177,-0.126046,0.343899
4,-0.677701,-0.838182,-0.479786,-0.290978,-0.185771,-0.434489,-0.125402,-0.434259,-0.001095,-0.179951,...,-0.426296,0.169085,-0.891651,-0.089003,-0.249682,0.985626,0.524944,0.027597,-0.191329,0.515223

In [27]:
modelo = XGBClassifier(learning_rate=0.2, n_estimators=500, max_depth=15)

modelo.fit(Xtrain, ytrain)
ypred = modelo.predict(Xtest)

print('Acurácia: {:.2f}%'.format(accuracy_score(ytest, ypred) * 100))

Acurácia: 94.87%